namespace SmartKb.Data.Entities;

/// <summary>
/// A maintenance task generated by automated pattern analysis — stale detection,
/// quality degradation, usage decline, or consolidation opportunities.
/// All tasks require human review before any action is taken.
/// P2-004: Pattern maintenance automation and contradiction detection.
/// </summary>
public sealed class PatternMaintenanceTaskEntity
{
    public Guid Id { get; set; }
    public string TenantId { get; set; } = string.Empty;

    /// <summary>The pattern this task applies to.</summary>
    public string PatternId { get; set; } = string.Empty;

    /// <summary>Type of maintenance: Stale, LowQuality, Unused, Consolidation.</summary>
    public string TaskType { get; set; } = string.Empty;

    /// <summary>Severity: Info, Warning, Critical.</summary>
    public string Severity { get; set; } = "Warning";

    /// <summary>Human-readable description of the maintenance issue.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Suggested action to resolve the task.</summary>
    public string RecommendedAction { get; set; } = string.Empty;

    /// <summary>JSON with supporting metrics (e.g., days since last use, quality score, usage count).</summary>
    public string MetricsJson { get; set; } = "{}";

    /// <summary>Status: Pending, Resolved, Dismissed.</summary>
    public string Status { get; set; } = "Pending";

    public string? ResolvedBy { get; set; }
    public DateTimeOffset? ResolvedAt { get; set; }
    public string? ResolutionNotes { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public TenantEntity Tenant { get; set; } = null!;
}
